### ISSUE TITLE
NPM 3?

### ISSUE THREAD

**Issue by developit** [kamicane/require-relative#2]
Hi there. I'm curious if this supports NPM 3's lookup algorithm out of the box.

I'm using it in [modify-babel-preset](https://github.com/developit/modify-babel-preset), but having some issues with NPM 3 that are very difficult to track down: developit/modify-babel-preset#2

**Comment by cspotcode** [comment]
Replying in case anyone else finds this issue:
This module uses node's own module resolution logic, which actually _isn't_ tied to npm 3 and didn't change when npm 3 was released.  So yes, this module should be unaffected by npm 3.

**Comment by developit** [comment]
Good to know. I wasn't sure if it would resolve to the top level module or not, but it doesn't seem tk matter!
